[package]
name = 'pea_protein_analysis'
version = '0.1.0'
edition = '2021'

[dependencies]
rand = "0.8"
rand_distr = "0.4"
rayon = "1.5"
statrs = "0.16"

[lib]
name = "pea_protein_analysis"
crate-type = ["cdylib"]
