[package]
name = "protein_analysis"
version = "0.1.0"
edition = "2021"

[lib]
name = "protein_analysis"
# This ensures consistent naming across platforms
crate-type = ["cdylib"]

[dependencies]
rand = "0.8"
rand_distr = "0.4"
rayon = "1.5"
statrs = "0.16"
