# Generated by Django 5.1.4 on 2025-01-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processanalysis',
            name='indirect_costs_factor',
            field=models.FloatField(default=0.15, help_text='Indirect costs factor'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='indirect_factors',
            field=models.JSONField(blank=True, help_text='List of indirect cost factors with names and values', null=True),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='installation_factor',
            field=models.FloatField(default=0.2, help_text='Installation cost factor'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='maintenance_factor',
            field=models.FloatField(default=0.05, help_text='Maintenance cost factor'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='market_growth_rate',
            field=models.FloatField(blank=True, help_text='Expected market growth rate', null=True),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='monte_carlo_iterations',
            field=models.IntegerField(default=1000, help_text='Number of Monte Carlo simulation iterations'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='price_volatility',
            field=models.FloatField(blank=True, help_text='Price volatility factor', null=True),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='process_stages',
            field=models.JSONField(blank=True, help_text='Data for each process stage', null=True),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='selling_price',
            field=models.FloatField(blank=True, help_text='Product selling price per kg in USD', null=True),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='stage_efficiencies',
            field=models.JSONField(blank=True, help_text='Efficiency metrics for each stage', null=True),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='target_protein_content',
            field=models.FloatField(blank=True, help_text='Target protein content in %', null=True),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='uncertainty',
            field=models.FloatField(default=0.1, help_text='Uncertainty factor for Monte Carlo simulation'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='utility_cost',
            field=models.FloatField(help_text='Utility cost per kWh in USD'),
        ),
    ]
