# Generated by Django 5.1.4 on 2025-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0003_alter_processanalysis_indirect_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='processanalysis',
            name='equipment_efficiency',
            field=models.FloatField(default=0.85, help_text='Equipment efficiency factor (0-1)'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='hours_per_week',
            field=models.IntegerField(default=40, help_text='Working hours per week'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='num_workers',
            field=models.IntegerField(default=1, help_text='Number of workers'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='revenue',
            field=models.JSONField(blank=True, help_text='Annual revenue projections', null=True),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='weeks_per_year',
            field=models.IntegerField(default=52, help_text='Working weeks per year'),
        ),
    ]
