# Generated by Django 5.1.4 on 2025-02-21 02:03

import process_data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0006_alter_analysisresult_economic_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processanalysis',
            name='equipment_cost',
        ),
        migrations.RemoveField(
            model_name='processanalysis',
            name='indirect_costs_factor',
        ),
        migrations.RemoveField(
            model_name='processanalysis',
            name='indirect_factors',
        ),
        migrations.RemoveField(
            model_name='processanalysis',
            name='installation_factor',
        ),
        migrations.RemoveField(
            model_name='processanalysis',
            name='labor_cost',
        ),
        migrations.RemoveField(
            model_name='processanalysis',
            name='maintenance_cost',
        ),
        migrations.RemoveField(
            model_name='processanalysis',
            name='maintenance_factor',
        ),
        migrations.RemoveField(
            model_name='processanalysis',
            name='raw_material_cost',
        ),
        migrations.RemoveField(
            model_name='processanalysis',
            name='utility_cost',
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='economic_factors',
            field=models.JSONField(default=dict, help_text='Economic factors including installation, indirect costs, maintenance factors, and project parameters'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='monte_carlo_iterations',
            field=models.IntegerField(default=1000, help_text='Number of iterations for Monte Carlo simulation'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='revenue_data',
            field=models.JSONField(default=dict, help_text='Revenue data including product price and annual production'),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='uncertainty',
            field=models.FloatField(default=0.1, help_text='Uncertainty factor for sensitivity analysis'),
        ),
        migrations.AlterField(
            model_name='processanalysis',
            name='equipment',
            field=models.JSONField(default=list, help_text='List of equipment with details including base cost, efficiency factor, installation complexity', validators=[process_data.validators.validate_equipment_structure]),
        ),
    ]
