# Generated by Django 5.1.4 on 2025-02-21 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0007_remove_processanalysis_equipment_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='processanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
